name: Build and push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-build:
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      image_name: 'pelias-api-docker-base'
      dockerfile: 'Dockerfile'
  docker-push:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1
    with:
      image_name: 'pelias-api-docker-base'
